### ISSUE TITLE
下载的数据最后多出一两行的内容

### ISSUE THREAD

**Issue by Deathin** [orzTech/HostsXEditor#16]
用了0.7.1.18版的hostsx后，更新hosts的三个数据，hostsx下载的数据相比从github上下载的原始数据有两个文件会在最后多出一两行的内容。
请尽快修复这个bug吧。
PS：这个bug是我个人的还是普遍的？

---

hosts文件_hostsx下载的
http://i.minus.com/ikuRd1SnD3t9k.jpg

hosts文件_github下载的
http://i.minus.com/iwOqBCtfumZQJ.jpg

sources文件_hostsx下载的
http://i1.minus.com/ibf0lAs4K30ayg.jpg

sources文件_github下载的
http://i.minus.com/ibdfg1y6ywDaHE.jpg

**Comment by orzFly** [comment]
所有在线功能已被移除。

**Comment by dragon100a** [comment]
> 所有在线功能已被移除。

突然收到一系列的邮件提示，这个东西后续还能更新吗？没有在线功能也好。

**Comment by orzFly** [comment]
目前暂时没有明确的维护计划。
